name: inductor-A100-perf-smoke-test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - .github/workflows/inductor-perf-smoke-test.yml
      - benchmarks/dynamo/check_hf_bert_perf_csv.py
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  linux-bionic-cuda11_6-py3_10-gcc7-inductor-build:
    name: cuda11.6-py3.10-gcc7-sm80
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-cuda11.6-py3.10-gcc7-sm80
      docker-image-name: pytorch-linux-bionic-cuda11.6-cudnn8-py3-gcc7
      cuda-arch-list: '8.0'
      test-matrix: |
        { include: [
          { config: "test_inductor_torchbench_smoketest_perf", shard: 1, num_shards: 1, runner: "linux.gcp.a100" },
        ]}

  linux-bionic-cuda11_6-py3_10-gcc7-inductor-test:
    name: cuda11.6-py3.10-gcc7-sm80
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-cuda11_6-py3_10-gcc7-inductor-build
    with:
      build-environment: linux-bionic-cuda11.6-py3.10-gcc7-sm80
      docker-image: ${{ needs.linux-bionic-cuda11_6-py3_10-gcc7-inductor-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-bionic-cuda11_6-py3_10-gcc7-inductor-build.outputs.test-matrix }}
      use-gha: anything-non-empty-to-use-gha
