name: unstable

on:
  push:
    branches:
      - master
      - main
    tags:
      - ciflow/unstable/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  # There must be at least one job here to satisfy GitHub action workflow syntax
  introduction:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Introduce PyTorch unstable workflow
        run: |
          echo "PyTorch unstable workflow is used to host experimental or flaky jobs"
          echo " that needs to be run for every commit, but doesn't block PR merging"
          echo " as part of the stable pull or trunk workflows."
          echo
          echo "In addition, a new label called ciflow/unstable can be attached to the"
          echo " PR to trigger this workflow. That can be done either manually or"
          echo " automatically using PyTorch auto-label bot."
          echo
          echo "Once the jobs are deemed stable enough (% red signal < 20% and TTS < 3h),"
          echo " they can graduate and move back to pull or trunk."

  linux-bionic-py3_7-clang8-xla-build:
    name: linux-bionic-py3_7-clang8-xla
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-py3_7-clang8-xla
      docker-image-name: xla_base
      test-matrix: |
        { include: [
          { config: "xla", shard: 1, num_shards: 1, runner: "linux.4xlarge" },
        ]}

  linux-bionic-py3_7-clang8-xla-test:
    name: linux-bionic-py3_7-clang8-xla
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-py3_7-clang8-xla-build
    with:
      build-environment: linux-bionic-py3_7-clang8-xla
      docker-image: ${{ needs.linux-bionic-py3_7-clang8-xla-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-bionic-py3_7-clang8-xla-build.outputs.test-matrix }}
