name: weekly

on:
  schedule:
    # Mondays at 7:37am UTC = 12:27am PST
    # Choose a random time near midnight PST because it may be delayed if there are high loads
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: 37 7 * * 1
  workflow_dispatch:

jobs:
  update-xla-commit-hash:
    uses: ./.github/workflows/_update-commit-hash.yml
    with:
      repo-name: xla
      branch: master
    secrets:
      MERGEBOT_TOKEN: ${{ secrets.MERGEBOT_TOKEN }}
      PYTORCHBOT_TOKEN: ${{ secrets.GH_PYTORCHBOT_TOKEN }}
